sudo: false
language: node_js
node_js:
  - 0.12
  - 4
  - 6
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  global:
    - CXX=g++-4.8
  matrix:
    - TARGET=test
    - TARGET=travis-coverage
script:
  - npm run $TARGET
