sudo: false
language: node_js
node_js:
  - 8
  - 10
  - 11
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
env:
  global:
    - CXX=g++-6
  matrix:
    - TARGET=test
    - TARGET=travis-coverage
script:
  - npm run $TARGET
