environment:
  matrix:
    - nodejs_version: "8.16.0"
    - nodejs_version: "8.16.0"
      USE_QLOBBER_PG: 1
    - nodejs_version: "10.15.3"
    - nodejs_version: "10.15.3"
      USE_QLOBBER_PG: 1
    - nodejs_version: "12.2.0"
    - nodejs_version: "12.2.0"
      USE_QLOBBER_PG: 1

install:
  - ps: Remove-NodeJsInstallation $(Get-InstalledNodeJsVersion).version $(Get-InstalledNodeJsVersion).bitness
  - ps: cmd /c start /wait msiexec /i $(Get-NodeJsInstallPackage $env:nodejs_version x64) /q
  - node --version
  - npm --version
  - npm install

test_script:
  - npm run test

build: off
